# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "addreas/elixir-app"
version = "0.0.8"
name = "Elixir Buildpack"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["wget", "unzip"]
