# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "app.elixir-buildpack"
version = "0.0.7"
name = "Elixir Buildpack"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
mixins = ["wget", "unzip"]
