# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "app.elixir-buildpack"
version = "0.0.1"
name = "Elixir Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"
